name: release

on:
  push:
    branches: [main]

jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install Dependencies
        run: npm install
      - name: Build App 
        run: npm run build
      - name: Publish app
        run: npm run make:macos
        env:
          GH_TOKEN: ${{secrets.PUBLISH}}

  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: Install Dependencies
        run: npm install
      - name: Build App 
        run: npm run build
      - name: Publish app
        run: npm run make:win
        env:
          GH_TOKEN: ${{secrets.PUBLISH}}

  build_on_ubuntu:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Using Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16.17.1
        - name: Install Dependencies
          run: npm install
        - name: Build App 
          run: npm run build
        - name: Publish app
          run: npm run make:linux
          env:
            GH_TOKEN: ${{secrets.PUBLISH}}